# Generated by Django 4.2.3 on 2023-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuffetCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_volume', models.DecimalField(decimal_places=3, max_digits=6)),
                ('food_calories', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
