# Generated by Django 4.2.3 on 2023-10-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_food_code_name_alter_food_info_food_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_info',
            name='cost',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
