# Generated by Django 4.2.3 on 2023-10-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_record_total_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail_record',
        ),
    ]
