# Generated by Django 4.2.3 on 2023-10-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_delete_detail_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fk_detailRecord_foodId', to='interface.food_code')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fk_detailRecord_recordId', to='interface.record')),
            ],
        ),
    ]
