# Generated by Django 4.2.3 on 2023-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_detail_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
