# Generated by Django 4.2.3 on 2023-10-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_food_code_food_info_provide_food_record_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_code',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food_info',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='fk_foodInfo_foodId', serialize=False, to='interface.food_code'),
        ),
        migrations.AlterField(
            model_name='provide_food',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='fk_prvideFood_name', serialize=False, to='interface.food_code', to_field='name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='detail_record',
            unique_together={('record_id', 'food_id')},
        ),
    ]
